/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as SettingsChangePasswordRouteImport } from './routes/settings/change-password'
import { Route as MarketsCreateRouteImport } from './routes/markets/create'
import { Route as MarketsMarketIdRouteImport } from './routes/markets/$marketId'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiCronWeeklyRecapRouteImport } from './routes/api/cron/weekly-recap'
import { Route as ApiCronWeeklyAllowanceRouteImport } from './routes/api/cron/weekly-allowance'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsChangePasswordRoute = SettingsChangePasswordRouteImport.update({
  id: '/settings/change-password',
  path: '/settings/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsCreateRoute = MarketsCreateRouteImport.update({
  id: '/markets/create',
  path: '/markets/create',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsMarketIdRoute = MarketsMarketIdRouteImport.update({
  id: '/markets/$marketId',
  path: '/markets/$marketId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronWeeklyRecapRoute = ApiCronWeeklyRecapRouteImport.update({
  id: '/api/cron/weekly-recap',
  path: '/api/cron/weekly-recap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronWeeklyAllowanceRoute = ApiCronWeeklyAllowanceRouteImport.update({
  id: '/api/cron/weekly-allowance',
  path: '/api/cron/weekly-allowance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rules': typeof RulesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/markets/create': typeof MarketsCreateRoute
  '/settings/change-password': typeof SettingsChangePasswordRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/': typeof UsersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/weekly-allowance': typeof ApiCronWeeklyAllowanceRoute
  '/api/cron/weekly-recap': typeof ApiCronWeeklyRecapRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rules': typeof RulesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/markets/create': typeof MarketsCreateRoute
  '/settings/change-password': typeof SettingsChangePasswordRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users': typeof UsersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/weekly-allowance': typeof ApiCronWeeklyAllowanceRoute
  '/api/cron/weekly-recap': typeof ApiCronWeeklyRecapRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rules': typeof RulesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/markets/create': typeof MarketsCreateRoute
  '/settings/change-password': typeof SettingsChangePasswordRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/': typeof UsersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/weekly-allowance': typeof ApiCronWeeklyAllowanceRoute
  '/api/cron/weekly-recap': typeof ApiCronWeeklyRecapRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rules'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/markets/$marketId'
    | '/markets/create'
    | '/settings/change-password'
    | '/users/$userId'
    | '/users/'
    | '/api/auth/$'
    | '/api/cron/weekly-allowance'
    | '/api/cron/weekly-recap'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rules'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/markets/$marketId'
    | '/markets/create'
    | '/settings/change-password'
    | '/users/$userId'
    | '/users'
    | '/api/auth/$'
    | '/api/cron/weekly-allowance'
    | '/api/cron/weekly-recap'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/rules'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/markets/$marketId'
    | '/markets/create'
    | '/settings/change-password'
    | '/users/$userId'
    | '/users/'
    | '/api/auth/$'
    | '/api/cron/weekly-allowance'
    | '/api/cron/weekly-recap'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RulesRoute: typeof RulesRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  MarketsMarketIdRoute: typeof MarketsMarketIdRoute
  MarketsCreateRoute: typeof MarketsCreateRoute
  SettingsChangePasswordRoute: typeof SettingsChangePasswordRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronWeeklyAllowanceRoute: typeof ApiCronWeeklyAllowanceRoute
  ApiCronWeeklyRecapRoute: typeof ApiCronWeeklyRecapRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/change-password': {
      id: '/settings/change-password'
      path: '/settings/change-password'
      fullPath: '/settings/change-password'
      preLoaderRoute: typeof SettingsChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/create': {
      id: '/markets/create'
      path: '/markets/create'
      fullPath: '/markets/create'
      preLoaderRoute: typeof MarketsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/$marketId': {
      id: '/markets/$marketId'
      path: '/markets/$marketId'
      fullPath: '/markets/$marketId'
      preLoaderRoute: typeof MarketsMarketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/weekly-recap': {
      id: '/api/cron/weekly-recap'
      path: '/api/cron/weekly-recap'
      fullPath: '/api/cron/weekly-recap'
      preLoaderRoute: typeof ApiCronWeeklyRecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/weekly-allowance': {
      id: '/api/cron/weekly-allowance'
      path: '/api/cron/weekly-allowance'
      fullPath: '/api/cron/weekly-allowance'
      preLoaderRoute: typeof ApiCronWeeklyAllowanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RulesRoute: RulesRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  MarketsMarketIdRoute: MarketsMarketIdRoute,
  MarketsCreateRoute: MarketsCreateRoute,
  SettingsChangePasswordRoute: SettingsChangePasswordRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  UsersIndexRoute: UsersIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronWeeklyAllowanceRoute: ApiCronWeeklyAllowanceRoute,
  ApiCronWeeklyRecapRoute: ApiCronWeeklyRecapRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
